POST http://localhost:3333/events
Content-Type: application/json

{
	"title": "Limited Event",
	"details": null,
	"maximumAttendees": 1
}

###

POST http://localhost:3333/events/53bbcaba-a09a-4aee-ba71-bd0370461c97/attendees
Content-Type: application/json

{
	"name": "Almeida",
	"email": "root@almeidx.dev"
}

###

GET http://localhost:3333/events/53bbcaba-a09a-4aee-ba71-bd0370461c97

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/53bbcaba-a09a-4aee-ba71-bd0370461c97/attendees?pageIndex=0&query=
